apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app.fullname" . }}
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
spec:
  type: LoadBalancer  # Change this to LoadBalancer
  ports:
    - port: 80          # External port for the service
      targetPort: http   # Internal container port
      protocol: TCP
  selector:
    {{- include "my-app.selectorLabels" . | nindent 4 }}
