apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app.fullname" . }}
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }} # Sets default to ClusterIP if not specified
  ports:
    - port: {{ .Values.service.port | default 80 }}      # Sets default port to 80 if not specified
      targetPort: {{ .Values.service.targetPort | default "http" }}  # Sets default targetPort to "http"
      protocol: TCP
      name: http
  selector:
    {{- include "my-app.selectorLabels" . | nindent 4 }}
