name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: neeraj46665/mosointerior:latest  # Docker Hub username and image name

      - name: SSH to EC2 and deploy to Minikube
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$EC2_SSH_KEY" > dovekey.pem
          chmod 600 dovekey.pem
          ssh -i dovekey.pem $EC2_USER@$EC2_HOST << 'EOF'
            # Clone the repository
            git clone https://github.com/neeraj46665/testing.git /home/ec2-user/my-app
            cd /home/ec2-user/my-app/k8s

            # Apply Kubernetes manifests
            kubectl apply -f deployment.yml
            kubectl apply -f service.yml

            # Port forward the service
            kubectl port-forward svc/mosointerior 3000:80 --address=0.0.0.0 &
          EOF
